export const ACCESS_TOKEN:string = "accessToken"
export const USER_LOGIN:string = "userLogin"
export const PROFILE:string= "profile"
export const ORDERHISTORY:string= "orderHistory"
export const ORDERDETAIL:string = "orderDetail"